#!/usr/bin/env node
// Dumps the linked Supabase project's public schema to supabase/schema.sql
// via the Management API (no Docker / DB password required).
//
// Auth: uses SUPABASE_ACCESS_TOKEN, ~/.supabase/access-token, or the
// CLI's keychain entry. Usage: node scripts/dump-schema.mjs

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const PROJECT_REF = 'elpdnxvtulbqgnsrbstx';
const OUT = new URL('../supabase/schema.sql', import.meta.url).pathname;

function getToken() {
  if (process.env.SUPABASE_ACCESS_TOKEN) return process.env.SUPABASE_ACCESS_TOKEN;
  const f = join(homedir(), '.supabase', 'access-token');
  if (existsSync(f)) {
    const t = readFileSync(f, 'utf8').trim();
    if (t) return t;
  }
  const raw = execSync('security find-generic-password -s "Supabase CLI" -w', { encoding: 'utf8' }).trim();
  if (raw.startsWith('go-keyring-base64:')) {
    return Buffer.from(raw.slice('go-keyring-base64:'.length), 'base64').toString('utf8');
  }
  return raw;
}

const TOKEN = getToken();

async function sql(query) {
  const res = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/database/query`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });
  if (!res.ok) throw new Error(`${res.status}: ${await res.text()}\nquery: ${query.slice(0, 200)}`);
  return res.json();
}

const sections = [];

// 1. Extensions
const exts = await sql(`
  select 'CREATE EXTENSION IF NOT EXISTS ' || quote_ident(extname) || ' WITH SCHEMA ' || quote_ident(n.nspname) || ';' as ddl
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
  where extname not in ('plpgsql') order by extname`);
sections.push('-- Extensions\n' + exts.map(r => r.ddl).join('\n'));

// 2. Enum types
const enums = await sql(`
  select 'CREATE TYPE public.' || quote_ident(t.typname) || ' AS ENUM (' ||
    string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) || ');' as ddl
  from pg_type t
  join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.typname order by t.typname`);
sections.push('-- Enum types\n' + (enums.map(r => r.ddl).join('\n') || '-- (none)'));

// 3. Tables (columns + defaults + not null + identity)
const tables = await sql(`
  select c.relname as table_name,
    'CREATE TABLE public.' || quote_ident(c.relname) || E' (\\n' ||
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
      || case when a.attidentity = 'a' then ' GENERATED ALWAYS AS IDENTITY'
              when a.attidentity = 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
              else coalesce(' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid), '') end
      || case when a.attnotnull then ' NOT NULL' else '' end,
      E',\\n' order by a.attnum
    ) || E'\\n);' as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = c.oid and ad.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname order by c.relname`);
sections.push('-- Tables\n' + tables.map(r => r.ddl).join('\n\n'));

// 4. Constraints (PK, UNIQUE, FK, CHECK) — FKs last so referenced tables exist
const cons = await sql(`
  select 'ALTER TABLE public.' || quote_ident(c.relname) || ' ADD CONSTRAINT ' ||
    quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';' as ddl,
    con.contype
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
  order by case con.contype when 'p' then 0 when 'u' then 1 when 'c' then 2 else 3 end, c.relname, con.conname`);
sections.push('-- Constraints\n' + cons.map(r => r.ddl).join('\n'));

// 5. Indexes (non-constraint)
const idxs = await sql(`
  select indexdef || ';' as ddl from pg_indexes i
  where schemaname = 'public'
    and not exists (
      select 1 from pg_constraint con
      join pg_class ic on ic.oid = con.conindid
      where ic.relname = i.indexname
    )
  order by tablename, indexname`);
sections.push('-- Indexes\n' + (idxs.map(r => r.ddl).join('\n') || '-- (none)'));

// 6. Views
const views = await sql(`
  select 'CREATE OR REPLACE VIEW public.' || quote_ident(c.relname) ||
    case when c.reloptions::text like '%security_invoker=true%' then ' WITH (security_invoker = true)' else '' end ||
    E' AS\\n' || pg_get_viewdef(c.oid, true) as ddl
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'v'
  order by c.relname`);
sections.push('-- Views\n' + (views.map(r => r.ddl).join('\n\n') || '-- (none)'));

// 7. Functions
const fns = await sql(`
  select pg_get_functiondef(p.oid) || ';' as ddl
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind = 'f'
  order by p.proname`);
sections.push('-- Functions\n' + (fns.map(r => r.ddl).join('\n\n') || '-- (none)'));

// 8. Triggers
const trgs = await sql(`
  select pg_get_triggerdef(t.oid, true) || ';' as ddl
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
  order by c.relname, t.tgname`);
sections.push('-- Triggers\n' + (trgs.map(r => r.ddl).join('\n') || '-- (none)'));

// 9. RLS enablement + policies
const rls = await sql(`
  select 'ALTER TABLE public.' || quote_ident(c.relname) || ' ENABLE ROW LEVEL SECURITY;' as ddl
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
  order by c.relname`);
const pols = await sql(`
  select 'CREATE POLICY ' || quote_ident(polname) || ' ON public.' || quote_ident(c.relname) ||
    case pol.polcmd when 'r' then ' FOR SELECT' when 'a' then ' FOR INSERT' when 'w' then ' FOR UPDATE' when 'd' then ' FOR DELETE' else ' FOR ALL' end ||
    ' TO ' || coalesce((select string_agg(rolname, ', ') from pg_roles where oid = any(pol.polroles)), 'public') ||
    coalesce(' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '') ||
    coalesce(' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '') || ';' as ddl
  from pg_policy pol
  join pg_class c on c.oid = pol.polrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
  order by c.relname, polname`);
sections.push('-- Row Level Security\n' + rls.map(r => r.ddl).join('\n') + '\n\n' + pols.map(r => r.ddl).join('\n'));

const header = `-- Parade — public schema snapshot
-- Generated by scripts/dump-schema.mjs via the Supabase Management API.
-- Project: ${PROJECT_REF}
-- NOTE: declarative reference snapshot, not a pg_dump. Regenerate after schema changes.
`;
writeFileSync(OUT, header + '\n' + sections.join('\n\n-- ============================================================\n') + '\n');
console.log(`Wrote ${OUT}`);
console.log(`Tables: ${tables.length}, constraints: ${cons.length}, indexes: ${idxs.length}, views: ${views.length}, functions: ${fns.length}, triggers: ${trgs.length}, RLS-enabled tables: ${rls.length}, policies: ${pols.length}`);
